# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-29 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20170829_1132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='desc',
            name='course',
        ),
        migrations.AddField(
            model_name='course',
            name='desc',
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name='Desc',
        ),
    ]
